// Simple mock product dataset to power filtering on category pages
// Fields align with `ProductCard` expectations and filter attributes

export const products = [
  {
    id: 101,
    name: "Black Striped T-shirt",
    price: 180,
    originalPrice: 242,
    discount: 25,
    image: "https://picsum.photos/300/300?random=201",
    rating: 4.5,
    color: "black",
    size: "Medium",
    style: "Casual",
    gender: "men",
    category: "T-shirts",
  },
  {
    id: 102,
    name: "White Casual T-shirt",
    price: 120,
    originalPrice: null,
    discount: null,
    image: "https://picsum.photos/300/300?random=202",
    rating: 4.0,
    color: "white",
    size: "Large",
    style: "Casual",
    gender: "men",
    category: "T-shirts",
  },
  {
    id: 103,
    name: "Red Hoodie",
    price: 210,
    originalPrice: 260,
    discount: 19,
    image: "https://picsum.photos/300/300?random=203",
    rating: 4.2,
    color: "red",
    size: "Large",
    style: "Gym",
    gender: "men",
    category: "Hoodie",
  },
  {
    id: 104,
    name: "Blue Denim Jeans",
    price: 240,
    originalPrice: 280,
    discount: 14,
    image: "https://picsum.photos/300/300?random=204",
    rating: 4.1,
    color: "blue",
    size: "Medium",
    style: "Casual",
    gender: "men",
    category: "Jeans",
  },
  {
    id: 105,
    name: "Green Shorts",
    price: 90,
    originalPrice: null,
    discount: null,
    image: "https://picsum.photos/300/300?random=205",
    rating: 3.8,
    color: "green",
    size: "Small",
    style: "Casual",
    gender: "men",
    category: "Shorts",
  },
  // Women
  {
    id: 201,
    name: "Floral Party Dress",
    price: 350,
    originalPrice: 400,
    discount: 12,
    image: "https://picsum.photos/300/300?random=301",
    rating: 4.8,
    color: "pink",
    size: "Medium",
    style: "Party",
    gender: "women",
    category: "Dresses",
  },
  {
    id: 202,
    name: "Elegant Formal Shirt",
    price: 212,
    originalPrice: 232,
    discount: 9,
    image: "https://picsum.photos/300/300?random=302",
    rating: 4.5,
    color: "white",
    size: "Small",
    style: "Formal",
    gender: "women",
    category: "Shirts",
  },
  {
    id: 203,
    name: "Casual Pants",
    price: 210,
    originalPrice: null,
    discount: null,
    image: "https://picsum.photos/300/300?random=303",
    rating: 4.2,
    color: "black",
    size: "Large",
    style: "Casual",
    gender: "women",
    category: "Pants",
  },
  {
    id: 204,
    name: "Yellow Summer T-shirt",
    price: 145,
    originalPrice: null,
    discount: null,
    image: "https://picsum.photos/300/300?random=304",
    rating: 3.9,
    color: "yellow",
    size: "Medium",
    style: "Casual",
    gender: "women",
    category: "T-shirts",
  },
  {
    id: 205,
    name: "Purple Gym Hoodie",
    price: 180,
    originalPrice: 200,
    discount: 10,
    image: "https://picsum.photos/300/300?random=305",
    rating: 4.0,
    color: "purple",
    size: "X-Large",
    style: "Gym",
    gender: "women",
    category: "Hoodie",
  },
  // More items to make filtering meaningful
  {
    id: 106,
    name: "Orange Gym Tee",
    price: 95,
    originalPrice: null,
    discount: null,
    image: "https://picsum.photos/300/300?random=206",
    rating: 3.7,
    color: "orange",
    size: "X-Small",
    style: "Gym",
    gender: "men",
    category: "T-shirts",
  },
  {
    id: 207,
    name: "Cyan Casual Tee",
    price: 110,
    originalPrice: null,
    discount: null,
    image: "https://picsum.photos/300/300?random=307",
    rating: 4.3,
    color: "cyan",
    size: "Small",
    style: "Casual",
    gender: "women",
    category: "T-shirts",
  },
];



